---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
 name: fortune-teller-ui
 namespace: my-apps
 labels:
  apps.tanzu.vmware.com/workload-type: web
  apps.tanzu.vmware.com/has-tests: "true"
  app.kubernetes.io/part-of: greeter
spec:
 build:
  env:
   - name: BP_JVM_VERSION
     value: "17"
   - name: BP_MAVEN_BUILT_MODULE
     value: "fortune-teller-ui"
 env:
  - name: SPRING_PROFILES_ACTIVE
    value: "development"
 serviceClaims:
  - name: eureka
    ref:
     apiVersion: services.apps.tanzu.vmware.com/v1alpha1
     kind: ResourceClaim
     name: eurekaserver-sample
 source:
  git:
   url: https://github.com/akrishna90/fortune-teller
   ref:
    branch: main